import 'package:flutter/material.dart';

class Tr {
  static String _currentLang = 'English';

  static void setLanguage(String langName) {
    _currentLang = langName;
  }

  static String get(String key) {
    final translations =
        _translations[_currentLang] ??
        _translations['English']!;
    return translations[key] ??
        _translations['English']![key] ??
        key;
  }

  static const Map<String, Map<String, String>>
      _translations = {
    'English': {
      'appName': 'RaastKar',
      'tagline': 'Smart Farming Solutions',
      'cropPlanner': 'Crop Planner',
      'cropPlannerDesc': 'AI-powered crop recommendations',
      'yourFarmDetails': 'Your Farm Details',
      'enterSoilData': 'Enter soil data for accurate results',
      'location': 'Location',
      'locationHint': 'e.g., Lahore, Multan, Karachi',
      'soilPh': 'Soil pH',
      'tds': 'TDS (ppm)',
      'salinity': 'Salinity (dS/m)',
      'analyze': 'Analyze & Get AI Recommendations',
      'analyzing': 'Analyzing...',
      'soilScore': 'Soil Suitability Score',
      'excellent': 'Excellent',
      'good': 'Good',
      'moderate': 'Moderate',
      'poor': 'Poor',
      'topRecommendations': 'Top Recommendations',
      'cropsFound': 'crops found',
      'aiAnalyzing': 'AI is analyzing your soil data...',
      'checkingCrop': 'Checking crop compatibility and market prices',
      'pleaseEnterLocation': 'Please enter your location',
      'pleaseFillAllValues': 'Please fill all soil values',
      'couldNotGet': 'Could not get recommendations',
      'connectionError': 'Connection error. Check backend.',
      'waterNeeds': 'Water need',
      'yield': 'Yield',
      'marketPrice': 'Market price',
      'season': 'Season',
      'drCrop': 'Dr Crop',
      'drCropDesc': 'AI-powered crop disease diagnosis',
      'selectCrop': 'Select Crop',
      'selectSymptoms': 'Select Symptoms',
      'diagnose': 'Diagnose',
      'diagnosing': 'Diagnosing...',
      'pleaseSelectSymptom': 'Please select at least one symptom',
      'symptomCheck': 'Symptom Check',
      'photoAnalysis': 'Photo Analysis',
      'takePhoto': 'Take Photo',
      'fromGallery': 'From Gallery',
      'noPhotoSelected': 'No photo selected',
      'takePhotoOrUpload': 'Take a photo or upload from gallery',
      'getDiagnosis': 'Get Diagnosis from RaastKar',
      'gettingDiagnosis': 'Getting Diagnosis...',
      'selectCropType': 'Select Crop Type',
      'describeSymptoms': 'Describe additional symptoms (optional)',
      'severityLevel': 'Severity Level',
      'organicTreatment': 'Organic Treatment',
      'chemicalTreatment': 'Chemical Treatment',
      'preventionSteps': 'Prevention Steps',
      'careRecommendations': 'Care Recommendations',
      'analyzingPhoto': 'AI is analyzing your photo...',
      'detectingDisease': 'Detecting disease from image using computer vision',
      'checkingDatabase': 'Checking disease database and treatment options',
      'weather': 'Commander Weather',
      'weatherDesc': 'Real-time alerts and crop recommendations',
      'enterCity': 'Enter city name',
      'activeAlerts': 'Active Alerts',
      'fiveDay': '5-Day Forecast',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'visibility': 'Visibility',
      'feelsLike': 'Feels like',
      'cropRecommendations': 'Crop Recommendations',
      'mandiPrices': 'Mandi Prices',
      'mandiDesc': 'Live market prices across Pakistan',
      'crop': 'Crop',
      'price': 'Price',
      'change': 'Change',
      'loadingPrices': 'Loading prices...',
      'couldNotLoadPrices': 'Could not load prices',
      'retry': 'Retry',
      'marketplace': 'Marketplace',
      'marketplaceDesc': 'Buy and sell directly with farmers',
      'searchCrops': 'Search crops, sellers...',
      'sellYourCrop': '🌱 Sell Your Crop',
      'contactSeller': 'Contact Seller',
      'productsFound': 'products found',
      'verifiedSellers': 'Verified Sellers',
      'postListing': '📢 Post My Listing',
      'addPhoto': 'Tap to add photo',
      'realPhotos': 'Real photos get more buyers!',
      'productTitle': 'Product title e.g. Fresh Wheat Grade A',
      'category': 'Category',
      'pricePKR': 'Price PKR/40kg',
      'bagsAvailableLabel': 'Bags available',
      'yourLocation': 'Your location e.g. Lahore',
      'whatsappNumber': 'Your WhatsApp number',
      'callNow': 'Call Now',
      'messageLabel': 'Message',
      'all': 'All',
      'grains': 'Grains',
      'vegetables': 'Vegetables',
      'fruits': 'Fruits',
      'carbonCredit': 'Carbon Credits',
      'carbonDesc': 'Earn money for sustainable farming',
      'farmSetup': 'Farm Setup',
      'greenPractices': 'Green Practices',
      'creditsTab': 'Credits',
      'farmLocation': 'Farm Location',
      'cropType': 'Crop Type',
      'farmSize': 'Farm Size',
      'nextGreenPractices': 'Next → Select Green Practices',
      'calculateCredits': 'Calculate Credits →',
      'yourCarbonCredits': '🌍 Your Carbon Credits',
      'totalCreditsHeader': 'Total Credits',
      'co2Removed': 'CO₂ Removed',
      'pkrValue': 'PKR Value',
      'usdValue': 'USD Value',
      'howToSell': 'How to Sell Carbon Credits',
      'tipsToIncrease': 'Tips to Increase Credits',
      'practicesSelected': 'practices selected',
      'morePractices': 'More practices = more credits',
      'setupFarmFirst': 'Set up your farm first',
      'goToFarmSetup': 'Go to Farm Setup tab to calculate',
      'goToFarmSetupBtn': 'Go to Farm Setup',
      'verraFormula': 'VERRA Formula Preview',
      'esg': 'ESG Compliance',
      'esgDesc': 'Environmental Social Governance score',
      'overview': 'Overview',
      'environment': 'Environment',
      'overallEsgScore': 'Overall ESG Score',
      'environmental': 'Environmental',
      'social': 'Social',
      'governance': 'Governance',
      'improvementTips': 'Improvement Tips',
      'whyEsgMatters': 'Why ESG Score Matters',
      'quickWins': 'Quick Wins to Improve Score',
      'tapToEdit': 'Tap to edit →',
      'howToImprove': 'How to improve:',
      'ratingScale': 'Rating Scale',
      'roiCalculator': 'ROI Crop Calculator',
      'roiDesc': 'Calculate profit & return on investment',
      'farmArea': 'Farm Area',
      'cropSelection': 'Crop Selection',
      'sowingHarvest': 'Sowing & Harvest Schedule',
      'yieldMarket': 'Yield & Market Data',
      'expenses': 'Expenses',
      'roiResults': 'ROI Results',
      'nextExpenses': 'Next → Enter Expenses',
      'nextResults': 'Next → View ROI Results',
      'profitable': '✅ Profitable!',
      'loss': '⚠️ Loss!',
      'netProfit': 'Net Profit',
      'netLoss': 'Net Loss',
      'grossRevenue': 'Gross Revenue',
      'totalCost': 'Total Cost',
      'profitMargin': 'Profit Margin',
      'breakEven': 'Break-even Price',
      'howToImproveRoi': 'How to improve ROI',
      'seedCost': 'Seed Cost (PKR/acre)',
      'landPrep': 'Land Preparation (PKR/acre)',
      'fertilizer': 'Fertilizer (PKR/acre)',
      'pesticide': 'Pesticide (PKR/acre)',
      'laborCost': 'Labor Cost (PKR/acre)',
      'employeeCost': 'Employee Fixed (PKR/acre)',
      'fuelCost': 'Fuel Cost (PKR/acre)',
      'transportation': 'Transportation (PKR/acre)',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'drCropShort': 'Dr Crop',
      'weatherShort': 'Weather',
      'mandi': 'Mandi',
      'market': 'Market',
      'carbon': 'Carbon',
      'esgShort': 'ESG',
      'profitCalculator': 'Profit Calculator',
      'liveCalculation': 'Live Credit Calculation',
      'totalPlants': 'Total plants',
      'co2Sequestered': 'CO2 sequestered',
      'baseCredits': 'Base credits',
      'bonusCredits': 'Bonus credits',
      'totalCreditsLabel': 'Total credits',
      'estimatedValue': 'Estimated value',
      'certificate': 'Certificate coming soon!',
      'downloadCertificate': 'Download Certificate',
      'registerFarm': 'Register Farm & Calculate Credits',
      'plantsPerAcre': 'Plants per Acre',
      'farmDetails': 'Farm Details',
      'myCredits': 'My Credits',
      'creditsEarned': 'credits earned',
      'couldNotGetRecommendations': 'Could not get recommendations',
      'livePrices': 'Live prices from major mandis',
      'areaInAcres': 'Area in Acres',
      'filterByType': 'Filter by type:',
      'selectACrop': 'Select a crop',
      'sowingMonth': 'Sowing Month',
      'harvestMonth': 'Harvest Month',
      'expectedYield': 'Expected Yield (last year) kg/acre',
      'raastkarYield': 'RaastKar Suggested Yield',
      'marketRate': 'Market Rate (PKR/40kg bag)',
      'productionCosts': 'Production Costs',
      'laborOperations': 'Labor & Operations',
      'totalExpense': 'Total Expense Summary',
      'perAcre': 'Per Acre',
      'total': 'Total',
      'revenueBreakdown': 'Revenue Breakdown',
      'expenseBreakdown': 'Expense Breakdown',
      'raastkarOptimized': 'RaastKar Optimized Yield',
      'optimizedRevenue': 'Optimized Revenue',
      'optimizedProfit': 'Optimized Profit',
      'optimizedROI': 'Optimized ROI',
      'canIncrease': 'RaastKar can increase profit by',
      'calcBreakdown': 'Calculation Breakdown',
      'howToSellCredits': 'How to Sell Carbon Credits',
      'lowest': 'Lowest',
      'average': 'Average',
      'highest': 'Highest',
      'treePlantation': '🌳 Tree Plantation',
      'organicFarming': '🌱 Organic Farming',
      'composting': '♻️ Composting',
      'biogasPlant': '⚡ Biogas Plant',
      'dripIrrigation': '💧 Drip Irrigation',
      'noCropBurning': '🔥 No Crop Burning',
      'solarWaterPump': '☀️ Solar Water Pump',
    },
    'Urdu': {
      'appName': 'راستکار',
      'tagline': 'سمارٹ فارمنگ سولیوشنز',
      'cropPlanner': 'فصل منصوبہ ساز',
      'cropPlannerDesc': 'AI سے چلنے والی فصل کی سفارشات',
      'yourFarmDetails': 'آپ کے فارم کی تفصیلات',
      'enterSoilData': 'درست نتائج کے لیے مٹی کا ڈیٹا درج کریں',
      'location': 'مقام',
      'locationHint': 'مثال: لاہور، ملتان، کراچی',
      'soilPh': 'مٹی کا pH',
      'tds': 'TDS (ppm)',
      'salinity': 'نمکینی (dS/m)',
      'analyze': 'تجزیہ کریں اور AI سفارشات حاصل کریں',
      'analyzing': 'تجزیہ ہو رہا ہے...',
      'soilScore': 'مٹی کی مناسبیت کا اسکور',
      'excellent': 'بہترین',
      'good': 'اچھا',
      'moderate': 'اوسط',
      'poor': 'خراب',
      'topRecommendations': 'بہترین سفارشات',
      'cropsFound': 'فصلیں ملیں',
      'aiAnalyzing': 'AI آپ کی مٹی کا تجزیہ کر رہا ہے...',
      'checkingCrop': 'فصل کی مطابقت اور مارکیٹ قیمتیں چیک ہو رہی ہیں',
      'pleaseEnterLocation': 'براہ کرم اپنا مقام درج کریں',
      'pleaseFillAllValues': 'براہ کرم تمام مٹی کی قدریں پُر کریں',
      'couldNotGet': 'سفارشات حاصل نہیں ہو سکیں',
      'connectionError': 'کنکشن کی خرابی',
      'waterNeeds': 'پانی کی ضرورت',
      'yield': 'پیداوار',
      'marketPrice': 'بازار قیمت',
      'season': 'موسم',
      'drCrop': 'ڈاکٹر فصل',
      'drCropDesc': 'AI سے فصل کی بیماری کی تشخیص',
      'selectCrop': 'فصل منتخب کریں',
      'selectSymptoms': 'علامات منتخب کریں',
      'diagnose': 'تشخیص کریں',
      'diagnosing': 'تشخیص ہو رہی ہے...',
      'pleaseSelectSymptom': 'کم از کم ایک علامت منتخب کریں',
      'symptomCheck': 'علامت چیک',
      'photoAnalysis': 'تصویر تجزیہ',
      'takePhoto': 'تصویر لیں',
      'fromGallery': 'گیلری سے',
      'noPhotoSelected': 'کوئی تصویر نہیں',
      'takePhotoOrUpload': 'تصویر لیں یا اپلوڈ کریں',
      'getDiagnosis': 'راستکار سے تشخیص حاصل کریں',
      'gettingDiagnosis': 'تشخیص ہو رہی ہے...',
      'selectCropType': 'فصل کی قسم منتخب کریں',
      'describeSymptoms': 'اضافی علامات بیان کریں (اختیاری)',
      'severityLevel': 'شدت کی سطح',
      'organicTreatment': 'نامیاتی علاج',
      'chemicalTreatment': 'کیمیائی علاج',
      'preventionSteps': 'روک تھام کے اقدامات',
      'careRecommendations': 'دیکھ بھال کی سفارشات',
      'analyzingPhoto': 'AI آپ کی تصویر کا تجزیہ کر رہا ہے...',
      'detectingDisease': 'کمپیوٹر وژن سے بیماری کا پتہ لگایا جا رہا ہے',
      'checkingDatabase': 'بیماری کا ڈیٹا بیس اور علاج چیک ہو رہا ہے',
      'weather': 'کمانڈر موسم',
      'weatherDesc': 'ریئل ٹائم الرٹ اور فصل کی سفارشات',
      'enterCity': 'شہر کا نام درج کریں',
      'activeAlerts': 'فعال الرٹ',
      'fiveDay': '5 دن کی پیشگوئی',
      'humidity': 'نمی',
      'wind': 'ہوا',
      'visibility': 'مرئیت',
      'feelsLike': 'محسوس ہوتا ہے',
      'cropRecommendations': 'فصل کی سفارشات',
      'mandiPrices': 'منڈی قیمتیں',
      'mandiDesc': 'پاکستان بھر میں لائیو مارکیٹ قیمتیں',
      'crop': 'فصل',
      'price': 'قیمت',
      'change': 'تبدیلی',
      'loadingPrices': 'قیمتیں لوڈ ہو رہی ہیں...',
      'couldNotLoadPrices': 'قیمتیں لوڈ نہیں ہو سکیں',
      'retry': 'دوبارہ کوشش',
      'marketplace': 'مارکیٹ پلیس',
      'marketplaceDesc': 'کسانوں کے ساتھ براہ راست خرید و فروخت',
      'searchCrops': 'فصلیں، بیچنے والے تلاش کریں...',
      'sellYourCrop': '🌱 اپنی فصل بیچیں',
      'contactSeller': 'بیچنے والے سے رابطہ کریں',
      'productsFound': 'مصنوعات ملیں',
      'verifiedSellers': 'تصدیق شدہ بیچنے والے',
      'postListing': '📢 اپنی فہرست پوسٹ کریں',
      'addPhoto': 'تصویر شامل کرنے کے لیے ٹیپ کریں',
      'realPhotos': 'اصل تصاویر سے زیادہ خریدار ملتے ہیں!',
      'productTitle': 'مصنوع کا عنوان',
      'category': 'زمرہ',
      'pricePKR': 'قیمت PKR/40kg',
      'bagsAvailableLabel': 'دستیاب بوریاں',
      'yourLocation': 'آپ کا مقام مثلاً لاہور',
      'whatsappNumber': 'آپ کا واٹس ایپ نمبر',
      'callNow': 'ابھی کال کریں',
      'messageLabel': 'پیغام',
      'all': 'سب',
      'grains': 'اناج',
      'vegetables': 'سبزیاں',
      'fruits': 'پھل',
      'carbonCredit': 'کاربن کریڈٹ',
      'carbonDesc': 'پائیدار کھیتی سے پیسہ کمائیں',
      'farmSetup': 'فارم سیٹ اپ',
      'greenPractices': 'سبز طریقے',
      'creditsTab': 'کریڈٹ',
      'farmLocation': 'فارم کا مقام',
      'cropType': 'فصل کی قسم',
      'farmSize': 'فارم کا سائز',
      'nextGreenPractices': 'اگلا → سبز طریقے منتخب کریں',
      'calculateCredits': 'کریڈٹ حساب کریں →',
      'yourCarbonCredits': '🌍 آپ کے کاربن کریڈٹ',
      'totalCreditsHeader': 'کل کریڈٹ',
      'co2Removed': 'CO₂ ہٹایا گیا',
      'pkrValue': 'PKR قدر',
      'usdValue': 'USD قدر',
      'howToSell': 'کاربن کریڈٹ کیسے بیچیں',
      'tipsToIncrease': 'کریڈٹ بڑھانے کی تجاویز',
      'practicesSelected': 'طریقے منتخب',
      'morePractices': 'زیادہ طریقے = زیادہ کریڈٹ',
      'setupFarmFirst': 'پہلے اپنا فارم سیٹ اپ کریں',
      'goToFarmSetup': 'حساب کرنے کے لیے فارم سیٹ اپ ٹیب پر جائیں',
      'goToFarmSetupBtn': 'فارم سیٹ اپ پر جائیں',
      'verraFormula': 'VERRA فارمولہ جائزہ',
      'esg': 'ESG تعمیل',
      'esgDesc': 'ماحولیاتی سماجی حکمرانی اسکور',
      'overview': 'جائزہ',
      'environment': 'ماحول',
      'overallEsgScore': 'مجموعی ESG اسکور',
      'environmental': 'ماحولیاتی',
      'social': 'سماجی',
      'governance': 'حکمرانی',
      'improvementTips': 'بہتری کی تجاویز',
      'whyEsgMatters': 'ESG اسکور کیوں اہم ہے',
      'quickWins': 'اسکور بہتر کرنے کے فوری طریقے',
      'tapToEdit': 'ترمیم کے لیے ٹیپ کریں →',
      'howToImprove': 'بہتری کا طریقہ:',
      'ratingScale': 'درجہ بندی کا پیمانہ',
      'roiCalculator': 'ROI فصل کیلکولیٹر',
      'roiDesc': 'منافع اور سرمایہ کاری کا حساب لگائیں',
      'farmArea': 'فارم کا رقبہ',
      'cropSelection': 'فصل کا انتخاب',
      'sowingHarvest': 'بوائی اور کٹائی کا شیڈول',
      'yieldMarket': 'پیداوار اور مارکیٹ ڈیٹا',
      'expenses': 'اخراجات',
      'roiResults': 'ROI نتائج',
      'nextExpenses': 'اگلا → اخراجات درج کریں',
      'nextResults': 'اگلا → ROI نتائج دیکھیں',
      'profitable': '✅ منافع بخش!',
      'loss': '⚠️ نقصان!',
      'netProfit': 'خالص منافع',
      'netLoss': 'خالص نقصان',
      'grossRevenue': 'مجموعی آمدنی',
      'totalCost': 'کل لاگت',
      'profitMargin': 'منافع کا مارجن',
      'breakEven': 'بریک ایون قیمت',
      'howToImproveRoi': 'ROI کیسے بہتر کریں',
      'seedCost': 'بیج کی لاگت (PKR/ایکڑ)',
      'landPrep': 'زمین کی تیاری (PKR/ایکڑ)',
      'fertilizer': 'کھاد (PKR/ایکڑ)',
      'pesticide': 'کیڑے مار دوا (PKR/ایکڑ)',
      'laborCost': 'مزدوری (PKR/ایکڑ)',
      'employeeCost': 'ملازم (PKR/ایکڑ)',
      'fuelCost': 'ایندھن (PKR/ایکڑ)',
      'transportation': 'نقل و حمل (PKR/ایکڑ)',
      'language': 'زبان',
      'selectLanguage': 'زبان منتخب کریں',
      'drCropShort': 'ڈاکٹر فصل',
      'weatherShort': 'موسم',
      'mandi': 'منڈی',
      'market': 'مارکیٹ',
      'carbon': 'کاربن',
      'esgShort': 'ESG',
      'profitCalculator': 'منافع کیلکولیٹر',
      'liveCalculation': 'لائیو کریڈٹ حساب',
      'totalPlants': 'کل پودے',
      'co2Sequestered': 'CO2 جذب',
      'baseCredits': 'بنیادی کریڈٹ',
      'bonusCredits': 'بونس کریڈٹ',
      'totalCreditsLabel': 'کل کریڈٹ',
      'estimatedValue': 'تخمینہ قدر',
      'certificate': 'سرٹیفکیٹ جلد آ رہا ہے!',
      'downloadCertificate': 'سرٹیفکیٹ ڈاؤن لوڈ کریں',
      'registerFarm': 'فارم رجسٹر کریں اور کریڈٹ حاصل کریں',
      'plantsPerAcre': 'فی ایکڑ پودے',
      'farmDetails': 'فارم کی تفصیلات',
      'myCredits': 'میرے کریڈٹ',
      'creditsEarned': 'کریڈٹ کمائے',
      'couldNotGetRecommendations': 'سفارشات حاصل نہیں ہو سکیں',
      'livePrices': 'بڑی منڈیوں سے لائیو قیمتیں',
      'areaInAcres': 'ایکڑ میں رقبہ',
      'filterByType': 'قسم کے مطابق فلٹر:',
      'selectACrop': 'فصل منتخب کریں',
      'sowingMonth': 'بوائی کا مہینہ',
      'harvestMonth': 'کٹائی کا مہینہ',
      'expectedYield': 'متوقع پیداوار (گزشتہ سال) kg/ایکڑ',
      'raastkarYield': 'راستکار کی تجویز کردہ پیداوار',
      'marketRate': 'مارکیٹ ریٹ (PKR/40kg)',
      'productionCosts': 'پیداواری اخراجات',
      'laborOperations': 'مزدوری اور کام',
      'totalExpense': 'کل اخراجات کا خلاصہ',
      'perAcre': 'فی ایکڑ',
      'total': 'کل',
      'revenueBreakdown': 'آمدنی کی تفصیل',
      'expenseBreakdown': 'اخراجات کی تفصیل',
      'raastkarOptimized': 'راستکار کی بہترین پیداوار',
      'optimizedRevenue': 'بہترین آمدنی',
      'optimizedProfit': 'بہترین منافع',
      'optimizedROI': 'بہترین ROI',
      'canIncrease': 'راستکار منافع بڑھا سکتا ہے',
      'calcBreakdown': 'حساب کی تفصیل',
      'howToSellCredits': 'کاربن کریڈٹ کیسے بیچیں',
      'lowest': 'کم ترین',
      'average': 'اوسط',
      'highest': 'زیادہ ترین',
      'treePlantation': '🌳 درخت لگانا',
      'organicFarming': '🌱 نامیاتی کھیتی',
      'composting': '♻️ کمپوسٹنگ',
      'biogasPlant': '⚡ بائیو گیس پلانٹ',
      'dripIrrigation': '💧 ڈرپ آبپاشی',
      'noCropBurning': '🔥 فصل نہ جلائیں',
      'solarWaterPump': '☀️ شمسی واٹر پمپ',
    },
  };
}